# Generated by Django 5.1.2 on 2024-11-25 09:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_course_student_coursebatch_coursesection_exam_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesection',
            old_name='parent_section',
            new_name='section_no',
        ),
        migrations.RemoveField(
            model_name='course',
            name='sub_subsection_alias',
        ),
        migrations.AddField(
            model_name='course',
            name='chapter_alias',
            field=models.CharField(default='Chapter', max_length=50),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='chapter_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.coursesection'),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='subsection_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='section_alias',
            field=models.CharField(default='Section', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='subsection_alias',
            field=models.CharField(default='Subsection', max_length=50),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='api.course'),
        ),
    ]
