# Generated by Django 5.1.2 on 2024-12-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_studentexamquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
