# Generated by Django 5.1.2 on 2024-12-04 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_question_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='question_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.questionoption'),
        ),
    ]
