# Generated by Django 5.1.2 on 2024-12-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_studentexam_exam_remove_studentexam_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexam',
            name='exam_end_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='exam_start_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='no_of_correct_answers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='no_of_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='result',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
