# Generated by Django 5.1.2 on 2025-06-03 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('resource_name', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='success', max_length=50)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('subscriber_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.CharField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=50, unique=True)),
                ('course_name', models.CharField(max_length=100, unique=True)),
                ('chapter_alias', models.CharField(default='Chapter', max_length=50)),
                ('section_alias', models.CharField(default='Section', max_length=50)),
                ('subsection_alias', models.CharField(default='Subsection', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.IntegerField(default=1)),
                ('student_id', models.IntegerField(default=1)),
                ('exam_start_date_time', models.DateTimeField(blank=True, null=True)),
                ('exam_end_date_time', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=10, null=True)),
                ('no_of_questions', models.IntegerField(blank=True, null=True)),
                ('no_of_correct_answers', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_studentexam',
            },
        ),
        migrations.CreateModel(
            name='StudentExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.IntegerField(default=1)),
                ('student_id', models.IntegerField(default=1)),
                ('question_id', models.IntegerField(default=1)),
                ('student_answer', models.JSONField()),
                ('is_correct', models.BooleanField()),
            ],
            options={
                'db_table': 'api_studentexamanswer',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('address_line1', models.TextField(blank=True, null=True)),
                ('address_line2', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('tax_type', models.CharField(blank=True, choices=[('GST', 'GST'), ('VAT', 'VAT')], max_length=100, null=True)),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=100)),
                ('subscription_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=50, unique=True)),
                ('batch_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('subsection_no', models.CharField(max_length=100)),
                ('section_name', models.CharField(max_length=100)),
                ('chapter_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='app.coursesection')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='app.course')),
                ('section_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='app.coursesection')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=100)),
                ('enrollment_based', models.BooleanField(default=False)),
                ('exam_date', models.DateField()),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('exclude_previous_exams', models.BooleanField(default=False)),
                ('question_per_section', models.IntegerField()),
                ('display_question_answer', models.BooleanField(default=False)),
                ('display_exam_result', models.BooleanField(default=False)),
                ('total_num_of_questions', models.IntegerField()),
                ('randomize_question', models.BooleanField(default=False)),
                ('default_marks_per_question', models.IntegerField(default=1)),
                ('pass_mark', models.IntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coursebatch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('exclude_sections', models.ManyToManyField(blank=True, related_name='excluded_exams', to='app.coursesection')),
                ('include_sections', models.ManyToManyField(blank=True, related_name='included_exams', to='app.coursesection')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('media_url', models.URLField(blank=True, null=True)),
                ('media_type', models.CharField(blank=True, choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], max_length=5, null=True)),
                ('question_type', models.CharField(choices=[('radio', 'Radio'), ('check', 'Check'), ('order', 'Order'), ('pair', 'Pair')], max_length=5)),
                ('question_answer', models.TextField(blank=True, null=True)),
                ('difficulty_level', models.IntegerField(choices=[(3, 'High'), (2, 'Medium'), (1, 'Low')])),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=8)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coursesection')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_text', models.TextField()),
                ('media_url', models.URLField(blank=True, null=True)),
                ('media_type', models.CharField(blank=True, choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], max_length=5, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='app.question')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('answer_option_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_option_text', models.TextField()),
                ('media_url', models.URLField(blank=True, null=True)),
                ('media_type', models.CharField(blank=True, choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], max_length=5, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question')),
                ('question_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.questionoption')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField()),
                ('enrollment_serial', models.IntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coursebatch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_serial_no', models.IntegerField()),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(max_length=50)),
                ('options', models.JSONField()),
                ('answers', models.JSONField()),
                ('is_correct', models.BooleanField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
        migrations.CreateModel(
            name='EQUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.subscriber')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question')),
            ],
            options={
                'unique_together': {('exam', 'question')},
            },
        ),
    ]
