from django.urls import path
from .views import (get_users, create_user, user_detail, get_courses, create_course, course_detail, get_course_sections, 
                    create_course_section, course_section_detail, get_course_batches, create_course_batch, course_batch_detail, 
                    get_questions, create_question, question_detail, get_question_options, create_question_option, question_option_detail, 
                    get_answer_options, create_answer_option, answer_option_detail, get_exams, create_exam, exam_detail, get_exam_questions, 
                    create_exam_question, exam_question_detail, get_students, create_student, student_detail, get_student_courses, 
                    create_student_course, student_course_detail, get_student_exams, create_student_exam, student_exam_detail, 
                    get_student_exam_questions,get_student_exam_answers, create_student_exam_answer, student_exam_answer_detail)

urlpatterns = [
    path('users/', get_users, name='get_users'),
    path('users/create/', create_user, name='create_user'),
    path('users/<int:pk>/', user_detail, name='user_detail'),
    path('courses/', get_courses, name='get_courses'),
    path('courses/create/', create_course, name='create_course'),
    path('courses/<int:pk>/', course_detail, name='course_detail'),
    path('course_sections/', get_course_sections, name='get_course_sections'),
    path('course_sections/create/', create_course_section, name='create_course_section'),
    path('course_sections/<int:pk>/', course_section_detail, name='course_section_detail'),
    path('course_batches/', get_course_batches, name='get_course_batches'),
    path('course_batches/create/', create_course_batch, name='create_course_batch'),
    path('course_batches/<int:pk>/', course_batch_detail, name='course_batch_detail'),
    path('questions/', get_questions, name='get_questions'),
    path('questions/create/', create_question, name='create_question'),
    path('questions/<int:pk>/', question_detail, name='question_detail'),
    path('question_options/', get_question_options, name='get_question_options'),
    path('question_options/create/', create_question_option, name='create_question_option'),
    path('question_options/<int:pk>/', question_option_detail, name='question_option_detail'),
    path('answer_options/', get_answer_options, name='get_answer_options'),
    path('answer_options/create/', create_answer_option, name='create_answer_option'),
    path('answer_options/<int:pk>/', answer_option_detail, name='answer_option_detail'),
    path('exams/', get_exams, name='get_exams'),
    path('exams/create/', create_exam, name='create_exam'),
    path('exams/<int:pk>/', exam_detail, name='exam_detail'),
    path('exam_questions/', get_exam_questions, name='get_exam_questions'),
    path('exam_questions/create/', create_exam_question, name='create_exam_question'),
    path('exam_questions/<int:pk>/', exam_question_detail, name='exam_question_detail'),
    path('students/', get_students, name='get_students'),
    path('students/create/', create_student, name='create_student'),
    path('students/<int:pk>/', student_detail, name='student_detail'),
    path('student_courses/', get_student_courses, name='get_student_courses'),
    path('student_courses/create/', create_student_course, name='create_student_course'),
    path('student_courses/<int:pk>/', student_course_detail, name='student_course_detail'),
    path('student_exams/', get_student_exams, name='get_student_exams'),
    path('student_exams/create/', create_student_exam, name='create_student_exam'),
    path('student_exams/<int:pk>/', student_exam_detail, name='student_exam_detail'),
    path('student_exam_questions/<int:exam_id>/', get_student_exam_questions, name='get_student_exam_questions'),
    path('student_exam_answers/', get_student_exam_answers, name='get_student_exam_answers'),
    path('student_exam_answers/create/', create_student_exam_answer, name='create_student_exam_answer'),
    path('student_exam_answers/<int:pk>/', student_exam_answer_detail, name='student_exam_answer_detail'),
]